### ISSUE TITLE
Atom No Longer launches after 1.47.0 Auto Update

### ISSUE THREAD

**Issue by OneSkiRalph** [atom/.github#17] opened 2020-05-22 16:20 UTC
Received this error when I launched Atom after auto update this morning.
Win 10 build 1087
![image](https://user-images.githubusercontent.com/4132641/82688236-873f8a00-9c26-11ea-8286-78ec1bed1c9e.png)

Thanks

**Comment by OneSkiRalph** [comment] 2020-05-22 16:22
Update:

I am able to launch 1.46.0 in the app-1.46.0 folder.

**Comment by lkashef** [comment] 2020-05-22 16:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20788. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lkashef** 2020-05-22 16:52 UTC
Labels: duplicate

**Comment by OneSkiRalph** [comment] 2020-05-22 17:11
That worked! Thanks for your rapid response.
I opened Atom for a quick look this am and then closed it in < 1 minute. I wonder if this caused the installation issue?
Have a good day.

**Comment by lkashef** [comment] 2020-05-22 22:00
You are most welcome 🙇‍♂️

This happens sometimes, we don't know the root cause yet (probably os related problems), but normally a fresh install solves the problem.
